name: Maven Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Java
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 22

    # Cache Maven dependencies
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build and Test
    - name: Build and Run Tests
      run: |
        mvn clean test | tee test-output.txt

    # Display the contents of the output for debugging
    - name: Display Test Output for Debugging
      run: |
        cat test-output.txt

    # Display Test Results in Terminal
    - name: Display Test Results
      run: |
        echo "-------------------------------------------------------"
        echo "T E S T S"
        echo "-------------------------------------------------------"
        tail -n 20 test-output.txt # Show the last 20 lines of the file

    # Upload Surefire Reports and Test Output
    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          target/surefire-reports/*.txt
          test-output.txt
